services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: retail_api
    ports:
      - "$FASTAPI_PORT:$FASTAPI_PORT"
    volumes:
      - ./retail.db:/app/retail.db
    restart: always

  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    container_name: retail_dashboard
    ports:
      - "$STREAMLIT_PORT:$STREAMLIT_PORT"
    depends_on:
      - api
    environment:
      - API_URL=$API_URL
    restart: always