version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: retail_api
    ports:
      - "8000:8000"
    volumes:
      - ./retail.db:/app/retail.db
    restart: always

  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    container_name: retail_dashboard
    ports:
      - "8501:8501"
    depends_on:
      - api
    environment:
      - API_URL=http://api:8000
    restart: always